### ISSUE TITLE
Bad value: order_amount

### ISSUE THREAD

**Issue by jonas-jaderberg** [umbraco/Umbraco.Commerce.PaymentProviders.Klarna#2]
I am upgrading from Vendr to UmbracoCommerce. Payments againt Klarna works in Vendr but not fully in my upgraded project.
When doing the payment against Klarna I get a 400 Bad Request. I can see from the logs from Klarna 

Http request failed. Response body: ""{ \"correlation_id\" : \"d65a0004-cb2e-4595-a80d-1d1d444a375c\", \"error_code\" : \"BAD_VALUE\", \"error_messages\" : [ \"Bad value: order_amount\" ] }""

I have compared the messages sent to Klarna and I can see that the orderline with "shipping_fee" is missing and that makes the order amount to mismatch. 

I have a discount rule active if the order value is over > X then a Reward with 100% off Order Shipment Price. If I turn off this rule then it works. 

I think  the problem could be this line 
KlarnaHppPaymentProvider.cs, line 110.

 if (ctx.Order.ShippingInfo.ShippingMethodId.HasValue && ctx.Order.ShippingInfo.TotalPrice.Value.WithTax > 0) 

The reward seams to set  ctx.Order.ShippingInfo.TotalPrice.Value to 0. Probably this was not the case in Vendr.

I think the line should be
 if (ctx.Order.ShippingInfo.ShippingMethodId.HasValue && ctx.Order.ShippingInfo.TotalPrice.WithoutAdjustments.WithTax > 0) 
If I look at the Mollie PaymentProvider it does exactly that.

**Comment by mattbrailsford** [comment]
Good spot. You are right that `WithoutAdjustments` should be used instead. I'll get this updated in the next round of changes.

**Comment by jonas-jaderberg** [comment]
I tested this in my own local branch of the repo and it does work.
